import { Barbell, ForkKnife, Waves } from '@phosphor-icons/react/dist/ssr'
import type { IconProps } from '@phosphor-icons/react'
import type { ComponentType } from 'react'
import { Logo } from '@/components/common/logo'
import { SpeciesArt } from '@/components/fish/species-art'
import { normaliseDashes } from '@/lib/format'
import { formatProtein, proteinFor } from '@/lib/nutrition'
import { resolveSpecies } from '@/lib/species'
import { discoverUrl } from '@/lib/qr'
import type { KnowledgeCard } from '@/lib/api/fish'
import type { components } from '@/lib/api/schema'

type Lot = components['schemas']['LotResponse']

/** The class the print stylesheet isolates. See `@media print` in globals.css. */
export const PRINT_CARD_CLASS = 'qr-print-card'

/**
 * The card a restaurant that won a lot prints and puts in front of its diners.
 *
 * Landscape, at the A6 ratio it prints at (148 x 105 mm), in one fixed shape on
 * every viewport, because the preview is the thing that will be printed. The
 * diner reads the fish: its local name, Latin name, taste, texture and
 * protein. The code in the bottom-left corner opens the fish's page in Fishora.
 *
 * The photograph is the species photograph from `lib/species.ts`, swapped in
 * one place when live-fish photography arrives. A species listed in
 * `QR_PHOTOS` prints a fixed photograph instead, with its credit.
 */
const QR_PHOTOS: Record<string, { src: string; credit: string }> = {
  gembolo: { src: '/gembolo-qr.jpg', credit: 'Photo: Reef Life Survey' },
}

export function QrCard({ lot, card }: { lot: Lot; card: KnowledgeCard | null }) {
  const label = lot.species_id.replace('species_', '')
  const species = resolveSpecies(label)
  const protein = proteinFor(label)
  const url = discoverUrl(lot.public_slug)
  const scientific = card?.scientific_name ?? species.scientificName
  const fixedPhoto = QR_PHOTOS[label]

  return (
    <article
      className={`${PRINT_CARD_CLASS} grid aspect-[148/105] w-[min(88vw,40rem)] grid-cols-[46%_1fr] overflow-hidden rounded-[var(--radius-card)] bg-white text-[#0b1f33]`}
    >
      {/* Left: the fish, with the code sitting in its bottom-left corner. */}
      <div className="relative">
        {fixedPhoto ? (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={fixedPhoto.src} alt={species.commonName} className="absolute inset-0 size-full object-cover" />
            <span className="absolute right-[3%] bottom-[2%] text-[0.5rem] text-white/80">{fixedPhoto.credit}</span>
          </>
        ) : (
          <SpeciesArt label={label} className="absolute inset-0" sizes="(max-width: 640px) 40vw, 18rem" showName={false} />
        )}
        <div
          data-testid="qr-code-fish"
          className="absolute bottom-[4%] left-[4%] flex w-[36%] flex-col items-center gap-1 rounded-lg bg-white p-1.5"
        >
          {/* A plain img, not next/image: generated by our own route at a size
              the card fixes, so there is nothing for the optimiser to pick. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={`/api/qr/${lot.public_slug}`} alt={`QR code for ${species.commonName}`} className="aspect-square w-full" />
          <span className="text-center text-[0.55rem] leading-tight">Scan to explore Fishora</span>
        </div>
        <p className="sr-only">{url}</p>
      </div>

      {/* Right: what the diner wants to know. */}
      <div className="flex min-w-0 flex-col gap-[3%] p-[5%]">
        <div className="flex items-center justify-between gap-2">
          <p className="text-[0.625rem] font-medium tracking-[0.08em] uppercase opacity-70">Fish Knowledge Card</p>
          <Logo className="shrink-0 text-[0.7rem]" />
        </div>
        <div>
          <h3 className="text-[clamp(1.5rem,5vw,2.25rem)] leading-none font-semibold">{species.commonName}</h3>
          {scientific && <p className="mt-1 text-[0.8rem] italic opacity-75">{scientific}</p>}
        </div>
        {/* Centred in the space under the name, as in the reference card,
            rather than pinned to the bottom with a gap above. */}
        <dl className="flex flex-1 flex-col justify-center gap-2">
          <Row icon={ForkKnife} label="Taste" value={card?.taste} />
          <Row icon={Waves} label="Texture" value={card?.texture} />
          <Row icon={Barbell} label="Protein / 100 g" value={protein ? formatProtein(protein) : null} />
        </dl>
      </div>
    </article>
  )
}

function Row({
  icon: Icon,
  label,
  value,
}: {
  icon: ComponentType<IconProps>
  label: string
  value: string | null | undefined
}) {
  return (
    <div className="flex items-start gap-2 rounded-lg border border-[#0b1f33]/15 px-2 py-1.5">
      <Icon size={16} className="mt-0.5 shrink-0" aria-hidden />
      <div className="min-w-0">
        <dt className="text-[0.625rem] font-medium uppercase opacity-70">{label}</dt>
        <dd className="line-clamp-2 text-[0.75rem] leading-snug">{value ? normaliseDashes(value) : '-'}</dd>
      </div>
    </div>
  )
}
